### ISSUE TITLE
Discussion: Solver refactoring and new features in staging.

### ISSUE THREAD

**Issue by noelchalmers** [paranumal/libparanumal#20]
I made a number of experimental changes in the staging branch that I would like some feedback on to make sure everyone is on board with the new code structure I've been making. **I'm using the acoustics solver as a prototype right now and other solvers are not yet fully updated.** Here's a list of the major changes you will find at this point:

1. The whole code has a new make system. Type make --help in the acoustics solver to see some build options.
2. The mesh structure, ogs, and paralmond have been moved into a separate libs/ folder and are built independently of the solvers.
3. The solvers and mesh have been refactored into C++ classes to play nice with the new OCCA (makes many files cleaner as well). 
4. The src/ folder has become core/ and now contains functions that will be useful in several solvers.
5. I've made a timeStepper class to avoid some repeated time stepping code in other solvers. I'll use the same idea for the linear solvers and perhaps preconditioners so they can be more modular. 
6. I've cleaned up our handling of settings. We use the same file format, but now settings must be added explicitly before they are queried or changed. Adding a new setting allows for including a description of the setting and a list of valid values if desired. See acousticsSettings.cpp for an example of how this is handled in the solver. (Thanks for the suggestion @aaustin141 !)
7. The occa::properties we use for the kernel compilation is set by the device, then mesh, and the solver so that we avoid recreating it in many places and hopefully avoid re-building kernels frequently when small options change.
8. Better error handling throughout.

Some things I'm still addressing while updating the remaining solvers: a) Universal memory pool.  b) Migrating what is still in the top okl/ folder. c) OCCA gives me some faults at the end of the main functions when destroying objects. 

Feedback is welcome @tcew , @AliKarakus , @aaustin141 . If these changes are going to cause a host of issues then we can discuss how I can change things around. The mempool in particular may be inconvenient once it's in place.

**Comment by tcew** [comment]
Overall I think this is a very positive refactor.

I have some comments:

1. When code is modularized it can cause increased data motion as upper level code pretzels to accommodate the lower level modularization.

2. If students were contributing to this code I would be wary of using C++. So far this has not been an issue as most contributors are more senior.

3. Each of the example solvers was added in a semi-orthogonal way to explore a different issue. This means that there is likely not going to be a lot of reuse of time steppers. A prime example is the  bns code which will require a bespoke set of time integrators - and special pml operations. 

4. Another example is the INS code which requires temporal splitting that is unique in the solvers.

5. We are writing a different INS code that solves a sequence of coupled stokes solves. The point being that the codes are not straight method of lines codes, in particular when DAE constraints are in play. Do you envision there being a library time stepper for each of the solvers ?

6. In the end my team needs a code that can be rapidly adjusted to explore a new idea. It is possible by making this more of an infrastructure code that it gets harder to make simple changes, or go in different directions.

Again - I think the changes you are proposing are good. I just want to make sure we can keep innovating...

6. By going C++ we make it more cumbersome for Fortran codes to connect to the library. Are you building a C wrapper ?

**Comment by tcew** [comment]
In the current libP code the hierarchy and modularization makes it quite challenging to go in and modify the elliptic solver to solve vector elliptic problems (think stokes with or without variable viscosity, but definitely without operator splitting). 

Since you are refactoring is it straight forward to make the elliptic solver handle multiple, possibly interdependent, elliptic solves ?

**Comment by nnnunnn** [comment]
Just a thought - this clean-up of support code could make it **easier** to focus on the solvers (i.e., "rapidly adjust / explore new ideas").

Regarding minimal use of C++ (tidy up a few structs, associate member data with member functions), does this cause major headaches for fortran?

Regarding students, the brighter ones will that notice C++ _"is just like Python"_  :-)

**Comment by tcew** [comment]
I am concerned about the Fortran interface issue. We can of course resort to void* malarky and passing vanilla arrays via pointer. This is an important thing to get right for our Fortran friends.

The issue of C++ and students  - by definition students are broadly not experienced in C++ - and the language contains many bear traps for the unsuspecting.
