### ISSUE TITLE
meshMinCharacteristicLengrh is simplex specific

### ISSUE THREAD

**Issue by tcew** [paranumal/libparanumal#25]
The meshMinCharacteristicLength 2D and 3D versions only appear to be suitable for triangles and tetrahedra respectively.

I think Quad2D and Hex3D versions may be warranted.

**Comment by noelchalmers** [comment]
We currently don't do any 'smart' setup of CFL numbers in the solvers, but once we do this will likely be more important to get right. I'll note this in my CFL number TODO item.
