### ISSUE TITLE
Halo Exchange Performance Problems

### ISSUE THREAD

**Issue by tcew** [paranumal/libparanumal#7]
Currently the halo exchange sends all the node data associated between ranks. This is very inefficient for higher order hex elements, representing (N+1) times too much data. Unfortunately this is causing poor scaling for data moved over PCI-E. 

To do: replace current whole element ghost with face trace ghost elements. This will require reworking vmapP, and the meshHaloExtract kernel.

**Comment by tcew** [comment]
I have added a prototype halo replacement in advection. The idea is to use haloGet and haloPut kernels that extract just the face nodes in the first case, and injects face nodes into full halo elements in the second case.

**Comment by noelchalmers** [comment]
Addressed in 585122e42adbb0c98e366f1063828302b65fd494. Solvers can construct general trace node exchanges with `mesh_t::HaloTraceSetup` method.
