### ISSUE TITLE
GPU Utilization

### ISSUE THREAD

**Issue by raj-brown** [paranumal/libparanumal#91]
Dear All-
I was running `ins` solver and I checked the GPU utilization and it was zero all the way and memory usage was 5 GB. Is there a way to measure the GPU Utilization from the code for different kernel such volume kernel and surface kernel.. 

Thanks!
Raj

**Comment by tcew** [comment]
Please run

``` ./occa/bin/occa  info ```

and verify that what GPU modes have been detected.

 You will likely have to modify the setup file to choose the correct backend mode and device.

**Comment by raj-brown** [comment]
@tcew yes I am setting up CUDA as backend like this 

```[MESH DIMENSION]
3
[ELEMENT TYPE] # number of edges
6
[POLYNOMIAL DEGREE]
3
[THREAD MODEL]
CUDA
[PLATFORM NUMBER]
0
[DEVICE NUMBER]
0
```
 And output of `./occa/bin/occa info` is in this [gist](https://gist.github.com/raj-brown/210a69494d7b11899f2003b14f558ca5). It detects GPU not sure why utilization is zero. Thank you!

**Comment by tcew** [comment]
Can you gist the output of:

```nvidia-smi```

**Comment by raj-brown** [comment]
yes Prof. This the [gist](https://gist.github.com/raj-brown/8a835ac149539a10797e8051b04a486b) while running the simulation. Thank you for looking into it.

**Comment by tcew** [comment]
ok. Next can you run ```ncu```

Something like

```
ncu --print-summary=per-kernel    ./foo   bah 
```

It should give you a summary of the performance of each kernel.

**Comment by raj-brown** [comment]
Sure @tcew I will do that as invoking `ncu` will require modifying the the `conf` file and restarting the workstation. I will do that and let you know. Thank you!

**Comment by tcew** [comment]
Also, can you provide a bit more info? Like how many elements are you using ?

**Comment by raj-brown** [comment]
yes sure Prof. @tcew. I will provide the details. Thank you!

**Comment by tcew** [comment]
Can I close this issue ?

**Comment by raj-brown** [comment]
Hi Prof. @tcew I was out of town but I will post more details about profiling by this weekend. Please dont close it.

Thanks!

**Comment by tcew** [comment]
Are we ok to close this ?

**Comment by raj-brown** [comment]
yes Prof. @tcew. Thank you very much!
